### PR TITLE
feat: new config format with .env and relative path support

### PR DESCRIPTION
**Pull request by stijn-gravity**

### CODE REVIEW

**Review by icazemier — APPROVED** [review]
Cuwl

**Comment by Erikdegroot89** [comment]
Calling it an [`rc` file](http://www.catb.org/~esr/writings/taoup/html/ch10s03.html) is a common practice we could consider using.
Also, I don't think it's common for `npx` scripts to read `.env` files, since they contain sensitive data. I don't have a better suggestion for reading the key though, other than CLI arguments.

**Comment by stijn-gravity** [comment]
@Erikdegroot89 the command won't read from .env itself but the idea is that people can put this env var in the config themselves, like we do here for the gva-cms i18next config: https://github.com/gravitybv/gva-cms/blob/development/next-i18next.config.js

**Comment by stijn-gravity** [comment]
@Erikdegroot89 also an rc file is actually supported in this. instead of poeditor-import.config.js they can name it .poeditor-importrc and it should work the same.

**Pull request merged**
